### ISSUE TITLE
examples/UpdateSSLCert.sh 执行问题

### ISSUE THREAD

**Issue by rudymemo** [Hill-98/aliyun-openapi-bash-sdk#1]
您好，我参考了您的examples/UpdateSSLCert.sh脚本，发现一段代码执行有问题
`# 检查环境变量是否存在
for value in "${ACME_ENV_LIST[@]}" ; do
   [[ ! -v "$value" ]] || exit 1
done`

这段循环里面的 ！符号是否应该去掉呢，我去掉之后可以行的通，如果理解有问题还望指正一下。

**Comment by Hill-98** [comment]
不好意思，这确实是个错误，感谢指正。
